
SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 600

SCREEN_WIDTH = 500
SCREEN_HEIGHT = 500

FRAME_RATE = 60

PLAYER_SURFACE_WIDTH = 25
PLAYER_SURFACE_HEIGHT = 25
PLAYER_SURFACE_COLOR = (255, 255, 255)
PLAYER_VELOCITY = 5
PLAYER_ACELERATION_CHANGE = 0.2

CAMERA_X_POS = 50
CAMERA_Y_POS = 50

## this should be removed in future versions setting can not define sprites groups
SPRITE_GROUPS = [
    'SceneObject',
    'Shot',
    'Player',
    'ICollidable'
]

HUD_MARGIN_X = 20
HUD_MARIGIN_Y = 20
HUD_PRIMARY_FONT = 'freesansbold'

HUD_PRIMARY_FONT_SIZE = 18
HUD_PRIMARY_FONT_PATH = 'fonts/PIXELADE.TTF'
HUD_POSITION = 0
HUD_COLOR = 1
HUD_CONFIG = {
    "SPEED": [(HUD_MARIGIN_Y, SCREEN_HEIGHT - 20), (134, 182, 246)]
}